### ISSUE TITLE
Constructor already exists

### ISSUE THREAD

**Issue by devmckeon** [acarl/pg-restify#13]
Upon requiring pg-restify I get the following error:
AssertionError [ERR_ASSERTION]: Constructor already exists!

I tried rolling back restify to 6.0.1 to see if it was some change to the restify API, but the error persists.
Any ideas?

**Comment by acarl** [comment]
It looks like you need to downgrade restify-errors to 5.0.0 as well. 

I just pushed a new version (0.5.0) with upgraded versions of restify and restify-errors so you won't have to worry about this.

**Comment by devmckeon** [comment]
Thank you!
