### ISSUE TITLE
Unexpected error: errnoException (dns.js:37:11)

### ISSUE THREAD

**Issue by krlng** [acarl/pg-restify#2]
I tried to get it up running, but I keep getting the same error all the time. Tried it with multiple databases on 2 different PostGres instances. Any ideas?

`{
    "name": "restify",
    "hostname": "XXX",
    "pid": 48027,
    "req_id": "8445ce73-d550-485d-88a6-21fbbbf9a2c0",
    "level": 50,
    "err": {
        "message": "getaddrinfo ENOTFOUND",
        "name": "Error",
        "stack": "Error: getaddrinfo ENOTFOUND\n    at errnoException (dns.js:37:11)\n    at Object.onanswer [as oncomplete] (dns.js:124:16)",
        "code": "ENOTFOUND"
    },
    "req": {
        "method": "GET",
        "url": "/api/generic/articles",
        "headers": {
            "host": "127.0.0.1:8081",
            "connection": "keep-alive",
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
            "upgrade-insecure-requests": "1",
            "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36",
            "accept-encoding": "gzip, deflate, sdch",
            "accept-language": "en-US,en;q=0.8,de;q=0.6",
            "cookie": "_ga=GA1.4.959001253.1396475979"
        },
        "remoteAddress": "127.0.0.1",
        "remotePort": 64076
    },
    "msg": "getaddrinfo ENOTFOUND",
    "time": "2015-09-06T22:11:30.234Z",
    "v": 0
}`

**Comment by acarl** [comment]
That's interesting. If the server starts without error then it shouldn't be an issue with the postgres connection. It appears that this is an issue when you actually make the first API request.

Could you provide some sample code for how you are initializing pg-restify? Do you configure any additional hooks or is it a pretty simple setup?

**Comment by krlng** [comment]
I am really sorry, of course it was my fault. I had a wrong connection string and just switched names and ip adressses etc. but not the format. Really sorry, thanks for your help
