### ISSUE TITLE
Add support for fields other than id

### ISSUE THREAD

**Issue by tomkel** [acarl/pg-restify#4]
In many cases, pg-restify assumes that the table being queried has an id field. It would be nice to specify the name of the field that pg-restify will use for the route endpoints.

**Comment by acarl** [comment]
Good point. I could add an optional configuration parameter called "tableIdColumns" which would be a map of actual database table name to database column name to be used as an index. If the table isn't specified it would default to "id" as it does now.

Here would be a sample value for this configuration value.

```
{
  "user_alert_messages": "user_name",
  "alerts": "alert_id"
}
```

Would that work for you?

**Comment by tomkel** [comment]
Yes, that would work.

**Comment by acarl** [comment]
The latest version (0.3.1) now has support for this. If you run into any issues let me know.
