### ISSUE TITLE
Support for json/jsonb fields update

### ISSUE THREAD

**Issue by Kostanos** [acarl/pg-restify#7]
Hi, I'm looking how can I update particular keys of JSON fields.

For example this will work in SQL:
```
UPDATE my_table SET data = data || jsonb_build_object('phone', '222-222-222') WHERE id=1
```

Ideas how can we add this?

**Comment by acarl** [comment]
This is an interesting use case. By default pg-restify is made to map a json passed to it to single columns. Have you tried calling a PUT with an escaped json string? 

```json
{
  "data": "{\"phone\":\"222-222-2222\"}"
}
```
