### ISSUE TITLE
Any ACL recommendations?

### ISSUE THREAD

**Issue by Kostanos** [acarl/pg-restify#9]
We need to limit pg-restify with ACL.

So public apps that uses pg-restify will be limited and will not be able to access restricted resources.

Any idea?

**Comment by acarl** [comment]
That's actually one of the main reasons I added the hooks API. You can prehook for all all resources and check something like a session cookie in the req object. You could use this to validate the request or even add a restriction to the where clause thanks to your recent changes.

It really depends on what you're trying to achieve.
